---
- name: 'Create container dir: {{ beacon_node_cont_name }}'
  file:
    path: '{{ beacon_node_cont_vol }}/data'
    state: directory
    owner: dockremap
    group: docker
    mode: 0750
  with_items:
    - '{{ beacon_node_cont_vol }}/data'
    - '{{ beacon_node_secrets_path }}'

- name: Create netkey file (optional)
  copy:
    dest: '{{ beacon_node_cont_vol  }}/{{ beacon_node_netkey_cont_path }}'
    content: '{{ beacon_node_netkey }}'
    owner: dockremap
    group: docker
    mode: 0600
  when: beacon_node_netkey is defined

- name: Create JSON RPC wrapper script
  template:
    src: 'rpc.sh.j2'
    dest: '{{ beacon_node_cont_vol }}/rpc.sh'
    owner: 'root'
    group: 'docker'
    mode: 0750
