---
- name: 'Consul service definition - {{ beacon_node_cont_name }}'
  include_role: name=consul-service
  vars:
    consul_config_name: '{{ beacon_node_consul_service_file_name }}'
    consul_services:
      - id: '{{ beacon_node_cont_name }}'
        name: '{{ beacon_node_consul_service_name }}'
        port: '{{ beacon_node_listening_port }}'
        address: '{{ beacon_node_public_address }}'
        tags: ['{{ env }}.{{ stage }}', 'beacon', 'nimbus']
        checks:
          - name: '{{ beacon_node_consul_service_name }}-health'
            type: 'script'
            script: '{{ beacon_node_cont_vol }}/rpc.sh get_v1_node_version'

      - id: '{{ beacon_node_cont_name }}-metrics'
        name: '{{ beacon_node_consul_metrics_service_name }}'
        port: '{{ beacon_node_metrics_port }}'
        address: '{{ ansible_local.tinc.vpn_ip }}'
        tags: ['{{ env }}.{{ stage }}', 'beacon', 'nimbus', 'metrics']
        meta:
          container: '{{ beacon_node_cont_name }}'
        checks:
          - name: '{{ beacon_node_consul_metrics_service_name }}-health'
            type: 'http'
            http: 'http://localhost:{{ beacon_node_metrics_port }}/metrics'
