FROM alpine:3.12.1 AS builder

RUN apk add --no-cache bash git build-base pcre-dev linux-headers

RUN git config --global pull.rebase false
RUN cd /opt && git clone https://github.com/status-im/nimbus-eth2

WORKDIR /opt/nimbus-eth2

RUN make update
RUN make deps

# This is to force rebuild from this point.
# We avoid re-doing most of `make update` and `make deps`.
ARG DUMMY

RUN git checkout .
RUN git checkout devel
RUN git pull

RUN make update
RUN make \
      LOG_LEVEL="TRACE" \
      MAKEFLAGS="-j2" \
      NIMFLAGS="-d:insecure -d:testnet_servers_image --parallelBuild:1" \
      beacon_node signing_process

FROM alpine:3.12.1

RUN apk add --no-cache libgcc pcre

COPY --from=builder /opt/nimbus-eth2/build/beacon_node /usr/local/bin/beacon_node

STOPSIGNAL SIGINT

ENTRYPOINT ["/usr/local/bin/beacon_node"]
